version: '3.8'
services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    ports:
      - ${QUORUM_API_PORT:-8000}:8000
    volumes:
      - ./api:/quorum
    depends_on:
      - postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB:?err}
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - SECRET_KEY=${QUORUM_API_SECRET_KEY:?err}

  postgres:
    image: postgres:16rc1-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - ${POSTGRES_DATA_PATH:-./data/postgres/}:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB:?err}
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
