# Generated by Django 4.2.6 on 2023-10-04 17:40

from django.db import migrations

from districts.models import NATIONAL


def insert_initial_values(apps, schema_editor):
    District = apps.get_model("districts", "District")
    names = [
        "Buenos Aires",
        "CABA",
        "Catamarca",
        "Chaco",
        "Chubut",
        "Corrientes",
        "Córdoba",
        "Entre Ríos",
        "Formosa",
        "Jujuy",
        "La Pampa",
        "La Rioja",
        "Mendoza",
        "Misiones",
        "Neuquén",
        "Río Negro",
        "Salta",
        "San Juan",
        "San Luis",
        "Santa Cruz",
        "Santa Fe",
        "Santiago del Estero",
        "Tierra del Fuego",
        "Tucumán",
    ]
    for name in names:
        District(name=name, is_national=False).save()
    District(name=NATIONAL, is_national=True).save()


class Migration(migrations.Migration):
    dependencies = [
        ("districts", "0002_district_is_national"),
    ]

    operations = [
        migrations.RunPython(insert_initial_values),
    ]
